[pytest]
markers = 
    smoke: pruebas críticas y rápidas
    exception: casos que validan manejo de errores
    operador: funcion de calculadora

python_files = test_*.py
python_functions = test_*

addopts = -v --html=report.html --self-contained-html 