[pytest]
markers = 
    smoke: pruebas críticas y rápidas
    exception: casos que validan manejo de errores
    login: pruebas relacionadas con el login
    pagproductos: Pruebas del armado de la pagina de productos
    carrito: pruebas relacionadas con el carrito de compras

    
pythonpath = .

python_files = test_*.py
python_functions = test_*

addopts = -v --self-contained-html 